version: 2.1
jobs:
  install:
    working_directory: ~/react-native-boilerplate
    docker:
      - image: circleci/node
    steps:
      - checkout

      - run:
          name: Install Yarn Dependencies
          command: yarn --frozen-lockfile

workflows:
  "Hello World":
    jobs:
      - install
