version: 2
jobs: 
  lint:
      machine: true
      steps:
          - run:
              name: Launch Test for begin
              command: yarn lint

workflows:
  version: 2
  lint:
      jobs:
          - lint


