version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node
    working_directory: ~/react-native-boilerplate

jobs:
  install:
    executor: node-executor
    steps:
      - checkout

  lint:
    executor: node-executor
    steps:
      - run: yarn install --frozen-lockfile

workflows:
  "Hello World":
    jobs:
      - install
      - lint:
          requires:
            - install
