version: 2
jobs: 
  test:
      machine: true
      steps:
          - run:
              name: Launch Test for begin
              command: ls

workflows:
  version: 2
  test:
      jobs:
          - test


