version: 2.1
jobs:
  install:
    working_directory: ~/react-native-boilerplate
    docker:
      - image: circleci/node
    steps:
      - checkout

      - restore_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - run:
          name: Install Yarn Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

  lint:
    working_directory: ~/react-native-boilerplate
    docker:
      - image: circleci/node

    steps:
      - run: yarn lint

workflows:
  "Hello World":
    jobs:
      - install
      - lint:
          requires:
            - install
