version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node
    working_directory: ~/react-native-boilerplate

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            ls -a .
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: node-executor
    steps:
      - run:
          name: Check Scripts
          command: |
            ls -a .
      - run: yarn install --frozen-lockfile

workflows:
  "Hello World":
    jobs:
      - install
      - lint:
          requires:
            - install
