version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node
    working_directory: ~/react-native-boilerplate

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - run:
          name: Install Yarn Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/react-native-boilerplate
      - run: yarn lint

workflows:
  "Default":
    jobs:
      - install
      - lint:
          requires:
            - install
